마이페이지 api 구현
Petionary/Backend pull request #16
Opened 2024-01-25 16:24 UTC by lby9906

1. 마이페이지 회원 정보를 보이게 기능 구현하였습니다.
2. 마이페이지 회원 정보 수정 가능하게 기능 구현하였습니다.
3. 회원 탈퇴 기능 구현하였습니다.

2024-01-29 15:37 UTC, cousim46 reviewed
기능 구현하시느라 고생많으셨습니다!
리뷰 남긴 내용 반영하고 말씀해주세요!
그리고 RestAPI 명명규칙을 지키려는 모습이 보여서 좋네요^^

2024-01-29 15:37 UTC, cousim46 commented on src/main/java/back/petionary/application/mypage/controller/MypageController.java
> +    }
해당 컨트롤러를 보면 mypage에 대한 API를 모아둔걸로 보입니다!
지금 모든 API에 공통적으로 mypage라는게 들어가는데
클래스단위에 @RequestMapping("/mypage")를 붙이셔서 중복을 제거하시는게 어떨가요!!

그리고 조회, 수정, 삭제를 HttpMethod + URL로 알려주고 계십니다!
즉 행위를 중복적으로 알려주고 있는것을 의미합니다!
이와 같이 바꿔보는게 어떨까요!


```java
 @PutMapping("/{id}")
@DeleteMapping("/{id}")
@GetMapping("/{id}")
```
이와 같이 수정을 하면 수정, 삭제, 조회 API를 HttpMethod로 쉽게 파악할 수 있어서 url에서는 삭제하셔도 될거같습니다!
대신 @PostMapping같은 경우에는 상황을 고려하면서 사용하면 좋을거 같습니다!

2024-01-29 15:37 UTC, cousim46 commented on src/main/java/back/petionary/application/mypage/service/MypageService.java
> +        Account account = accountRepository.findById(accountId).get();
지금 현재 findById.get()을 하고 계십니다!
findById를 하게될 경우 반환 객체는 Optional<객체>입니다.
Optional로 감싼 이유는 NPE를 방지하기 위해 감싸는것인데 get()을 해버릴경우 NPE 방지 역할을 할 수 없습니다! 만약 찾으려는 데이터가 없을 경우에는 CustomException 또는 다른 행위를 하도록 로직을 구현하시는게 좋을거 같습니다!

2024-01-29 15:51 UTC, lby9906 commented on src/main/java/back/petionary/application/mypage/controller/MypageController.java
> +    }
@RequestMapping 쓰니까 확실히 간결해지네요!
수정하겠습니다!

2024-02-02 12:01 UTC, lby9906 commented on src/main/java/back/petionary/application/mypage/service/MypageService.java
> +        Account account = accountRepository.findById(accountId).get();
수정하도록 하겠습니다.

2024-02-02 12:06 UTC, lby9906 commented
코드 리뷰 반영하여 마이페이지 api 다시 수정하였습니다.
확인하고 피드백 부탁드립니다!

2024-02-02 12:46 UTC, cousim46 requested changes
리뷰 반영하시느라 고생하셨습니다! 추가리뷰 남겼슺니다!

2024-02-02 12:46 UTC, cousim46 commented on src/main/java/back/petionary/Exception/CustomException.java
> +public class CustomException extends RuntimeException{
커스텀 익셉션 만들셨네요! 그런데 클래스명이 좀 아쉬운거 같아요! 프러젝트 이름이 Petionary니깐 PetionaryException으로 변경하면 어떨까요!

2024-02-02 12:46 UTC, cousim46 commented on src/main/java/back/petionary/application/mypage/dto/request/MypageAccountInfoRequest.java
> +public class MypageAccountInfoRequest {
지금 요청DTO랑 응답DTO를 각각 다른파일로 만드셨네요! DTO 관리를 어떻게하는게 효율적일지 회의를 해서 정하면 좋을거 같아요!

2024-02-02 12:46 UTC, cousim46 commented on src/main/java/back/petionary/application/mypage/service/MypageService.java
> +    @Transactional
지금 메서드별로 @Transactional을 붙여주셨는데 클래스단위에 한번만 붙여주는게 어떨까요!

2024-02-02 12:46 UTC, cousim46 commented on src/main/java/back/petionary/application/mypage/controller/MypageController.java
> +    public String mypageUpdateUserInfo(@PathVariable Long id, @RequestBody MypageAccountInfoRequest mypageAccountInfoRequest) {
메서드명을 동사로 하는게 좋을거 같아요! 
mypageAccountInfoResponse보다는 
getAccountInfo로 하면 어떨까요!
저 같은 경우는 조회를 하는 메서드는 get 또는 find로 짓는경우가 많은거 같아요! 그런데 get과 find로 메서드명을 지을때 상황마다 다르게 해야하기때문에 이거에 대해서는 조사해서 반영하면 좋을거 같습니다!

mypageUpdateUserInfo보다 updateAccountInfo로 하는게 어떨까요!

2024-02-02 12:46 UTC, cousim46 commented on src/main/java/back/petionary/application/mypage/service/MypageService.java
> +        Account account = accountRepository.findById(accountId).orElseThrow(() -> new CustomException("Account not found with id: " + accountId));
CustomException을 잘 활용해주셨네요..! 굳굳

2024-02-02 12:52 UTC, lby9906 commented
다시 수정하였습니다.
확인하고 피드백 부탁드립니다.

2024-02-02 13:15 UTC, lby9906 commented
코드 리뷰를 못본 부분이 있어 다시 수정하여 반영하였습니다.
확인하고 피드백 부탁드립니다.

2024-02-02 13:22 UTC, lby9906 commented
다시 수정하여 반영하였습니다.
확인하여 피드백 부탁드립니다.

2024-02-02 13:38 UTC, merged