유저 엔티티 생성
Petionary/Backend pull request #2
Opened 2023-07-22 12:25 UTC by cousim46

- 유저 엔티티와 유저 생성에 관한 테스트 코드를 작성하였습니다.

2023-07-22 13:28 UTC, ohgillwhan requested changes
코드 잘 봤습니다. 리뷰 확인해주세요.

2023-07-22 13:28 UTC, ohgillwhan commented on src/main/java/back/petionary/account/entity/Account.java
> +@NoArgsConstructor
개인적으로 @Getter, @NoArgsConstructor는 @Entity 위에 있으면 좋겠네요.

2023-07-22 13:28 UTC, ohgillwhan commented on src/main/java/back/petionary/account/entity/Account.java
> +    private Address address;
length 지정 및 annotation이 붙은 필드는 서로 떄주면 좋을것 같아요.

2023-07-22 13:28 UTC, ohgillwhan commented on src/main/java/back/petionary/account/entity/Account.java
> +        this.email = Objects.requireNonNull(email,"값이 존재하지 않습니다."); // 커스텀 예외로 변경
, 사이에 공백 추가해볼까요?

2023-07-22 13:28 UTC, ohgillwhan commented on src/main/java/back/petionary/account/entity/Address.java
> +    private String detail; //상세주소
얘내들도 @Column 붙여야 하지 않나요?

2023-07-22 13:28 UTC, ohgillwhan commented on src/main/resources/application.yml
> +spring:
실제 배포할 때 이 환경으로 배포하실껄가요?
아니라면, profile에 맞게 작성해볼까요.

2023-07-22 13:28 UTC, ohgillwhan commented on src/test/java/back/petionary/account/entity/AccountTest.java
> +    void test1() {
테이밍이 조금 아쉽네요.

2023-07-22 13:28 UTC, ohgillwhan commented on src/test/java/back/petionary/account/entity/AccountTest.java
> +    @DisplayName("이메일, 번호, 주소, 이름, 생년월일 빈값 하나라도 존재하면 예외가 발생한다.")
테스트코드에서는 email이 null일 때만 체크하고 있네요. 테스트코드 보강 해야할것 같네요.

2023-07-22 13:28 UTC, ohgillwhan commented on src/test/java/back/petionary/account/entity/AccountTest.java
> +        assertThat(message).isEqualTo("값이 존재하지 않습니다.");
메세지로 검증은 매우 위험합니다.
custom exception을 만들어보죠.

2023-07-22 13:35 UTC, cousim46 commented on src/test/java/back/petionary/account/entity/AccountTest.java
> +        assertThat(message).isEqualTo("값이 존재하지 않습니다.");
아! 넵 알겠습니다! 감사합니다

2023-07-22 14:42 UTC, cousim46 commented on src/main/resources/application.yml
> +spring:
수정했습니다!

2023-07-22 17:32 UTC, cousim46 commented on src/test/java/back/petionary/account/entity/AccountTest.java
> +    @DisplayName("이메일, 번호, 주소, 이름, 생년월일 빈값 하나라도 존재하면 예외가 발생한다.")
추가했습니다!

2023-07-22 17:33 UTC, cousim46 commented on src/test/java/back/petionary/account/entity/AccountTest.java
> +    void test1() {
수정하였습니다!

2023-07-23 06:26 UTC, ohgillwhan requested changes
리뷰 확인 부탁드립니다.

2023-07-23 06:26 UTC, ohgillwhan commented on src/main/java/back/petionary/account/entity/Address.java
> +    private String validate(String element) {
사이 공백 떼어주세요.

2023-07-23 06:26 UTC, ohgillwhan commented on src/main/java/back/petionary/account/entity/Account.java
> +        this.email = nullValidate(email);
함수명은 동사로

2023-07-23 06:26 UTC, ohgillwhan commented on src/main/java/back/petionary/account/entity/Account.java
> +    @Column(nullable = false)
다 255글자로  하실껀가요?

2023-07-23 06:26 UTC, ohgillwhan commented on src/main/java/back/petionary/account/entity/Address.java
> +            throw new CustomException(CustomErrorCode.NOT_VALUE);
커스텀익셉션? 뭔가 더 좋은 이름은 없을까요?

2023-07-23 06:26 UTC, ohgillwhan commented on src/main/java/back/petionary/account/entity/Address.java
> +            throw new CustomException(CustomErrorCode.NOT_VALUE);
그리고 해당 코드는 BaseEntity에도 있네요.
core라는 패키지를 만들거나 VALDATION이라는 패키지를 만들어서 그 안에 유틸성으로 둬도 괜찮아 보여요.

2023-07-23 06:26 UTC, ohgillwhan commented on src/main/java/back/petionary/account/entity/Address.java
> +
불필요한 공백 2개

2023-07-23 06:26 UTC, ohgillwhan commented on src/main/java/back/petionary/common/exception/CustomException.java
> +
불필요한공백~

2023-07-23 06:26 UTC, ohgillwhan commented on src/test/java/back/petionary/account/entity/AccountTest.java
> +        assertThrows(CustomException.class,() -> new Account(email, phone, name, birth, address));
코드도 비교하면 좋겠네요. (다른테스트코드도 동일)

2023-07-31 12:23 UTC, wooogiekim requested changes
리뷰 남겼습니다.
코멘트 확인해주시면 좋겠습니다.

2023-07-31 12:23 UTC, wook87 commented on src/main/java/back/petionary/account/entity/Account.java
> +public class Account extends BaseEntity{
띄어쓰기 필요합니다

```suggestion
public class Account extends BaseEntity {
```

2023-07-31 12:23 UTC, wook87 commented on src/main/java/back/petionary/account/entity/Account.java
> +        this.email = Validation.validateNull(email);
validate은 보통 리턴하지 않는 관례가 있습니다 혼동을 줄거같아요

2023-07-31 12:23 UTC, wook87 commented on src/main/java/back/petionary/common/exception/type/CommonErrorCode.java
> +    private String message;
에러와 사용자에게 나갈 메시지 분류가 없네요

2023-07-31 12:23 UTC, wooogiekim commented on src/test/java/back/petionary/account/entity/AccountTest.java
> +        assertThat(commonException.getErrorCode().getStatus()).isEqualTo(HttpStatus.BAD_REQUEST);
assertThat 만으로도 가능할거같아요 방법을 모색해보세요 ㅎ

2023-07-31 12:23 UTC, wooogiekim commented on src/test/java/back/petionary/account/entity/AccountTest.java
> +            () ->new Address(zipcode, detail));
```suggestion
            () -> new Address(zipcode, detail));
```

이런 부분은 리포맷팅 돌렸으면 나오지 않을 부분이라 아쉽네요

2023-07-31 12:23 UTC, wooogiekim commented on src/test/java/back/petionary/account/entity/AccountTest.java
> +        String name = "가나다라마바사아자차카타파하가나다라마바사아자차카타파하하하하";
스트링에 리핏이라는 메소드가 있습니다 이용하면 좋겠고

30이라는 구체적인 값이 나왔다면 상수로 관리하고 테스트에서도 이용하면 어떨까요?

2023-07-31 12:23 UTC, wooogiekim commented on src/main/java/back/petionary/common/exception/ExceptionControllerAdvice.java
> +    }
컨트롤러가 나왔나요? 안나왔다면 미리 이런 행동 안해도 될거같습니다.

2023-08-01 14:21 UTC, cousim46 commented on src/main/java/back/petionary/account/entity/Account.java
> +        this.email = Validation.validateNull(email);
그럴거 같네요! 수정하겠습니다!

2023-08-01 14:22 UTC, cousim46 commented on src/main/java/back/petionary/common/exception/ExceptionControllerAdvice.java
> +    }
해당 부분은 컨트롤러가 아직 안나왔으나 유저를 생성할때 예외를 발생시켜 만들었는데 불필요할까요?

2023-08-02 05:04 UTC, wook87 commented on src/main/java/back/petionary/common/exception/ExceptionControllerAdvice.java
> +    }
아직 나올때가 아니라고 생각들긴합니다.

PR 명이 유저 엔티티 생성인데

하려는 범위를 넘어서고 있다는 생각이 드네요

2023-08-06 03:41 UTC, wook87 approved these changes
고생하셨습니다.
리뷰 커스컴예외 관련 리뷰 드린 부분 생각한번해봐주시고
PR명의 범위에 넘어간 부분은 안하도록 자제하면서 만드는게 좋을거같습니다.

2023-08-13 12:03 UTC, cousim46 commented
PR 범위 넘는 코드 및 파일 삭제하였습니다.
리뷰해주셔서 감사합니다 :)

2023-08-13 12:03 UTC, merged