feature : 분실 신고 등록 및 조회 api
Petionary/Backend pull request #28
Opened 2024-03-21 11:40 UTC by lby9906

- 분실 신고 등록 api를 구현하였습니다.
- 분실 신고 조회 (상세보기 및 전체) api를 구현하였습니다.

2024-03-21 11:40 UTC, lby9906 commented
분실 신고 api 구현하였습니다.
확인하고 피드백 부탁드립니다.

2024-03-22 11:54 UTC, cousim46 requested changes
고생하셨습니다! 코드리뷰에 대해서 이해가 잘 안되는 내용이 있으시면 언제든 문의주세요~

2024-03-22 11:54 UTC, cousim46 commented on src/main/java/back/petionary/application/loss/service/ReportLossReadService.java
> +        ReportLoss reportLoss = reportLossRepository.findByIdAndAccountId(reportLossId, accountId).orElseThrow(() -> new PetionaryException("회원 id에 해당하는 게시물을 찾지 못했습니다."));
해당 메서드를 사용하는 API는 분실신고 상세보기인데 왜 회원아이디와 분신신고 id로 분실신고건을 조회해오시는걸까요??
이렇게 하게되면 분실신고를 등록한 사람만 볼 수 있는건데 이 의도로 코드를 작성하신걸까요?

2024-03-22 11:54 UTC, cousim46 commented on src/main/java/back/petionary/domain/loss/entity/ReportLoss.java
> +        this.lossLocation = lossLocation;
해당 메서드는 어디에서 지금 사용되고 있는걸까요?

2024-03-22 11:54 UTC, cousim46 commented on src/main/java/back/petionary/application/loss/dto/response/ReportLossResponse.java
> +    private LocalDate petAge;
펫 나이라고 적어주셨는데 1살 2살을 나타내는걸까요? 아니면 '1998-10-15' 이런 형식을 나타내는걸까요?
만약 1살 2살이면 데이터 타입을 변경해주시고 후자일 경우는 '펫 출생년도'로 표현하시는게 좋을거 같아요!

2024-03-22 11:54 UTC, cousim46 commented on src/main/java/back/petionary/application/loss/service/ReportLossReadService.java
> +                .map(page -> new ReportLossListResponse(page.getFeature(), page.getAccount().getNickName(), page.getLossLocation()))
page라는 변수보다는 report라는 변수가 좋을거 같아요~

2024-03-22 11:57 UTC, lby9906 commented on src/main/java/back/petionary/domain/loss/entity/ReportLoss.java
> +        this.lossLocation = lossLocation;
제가 수정을 못했네요 바로 삭제하겠습니다.

2024-03-22 11:57 UTC, lby9906 commented on src/main/java/back/petionary/application/loss/dto/response/ReportLossResponse.java
> +    private LocalDate petAge;
넵 알겠습니다!

2024-03-22 11:58 UTC, lby9906 commented on src/main/java/back/petionary/application/loss/service/ReportLossReadService.java
> +                .map(page -> new ReportLossListResponse(page.getFeature(), page.getAccount().getNickName(), page.getLossLocation()))
그렇네요! 수정하겠습니다.

2024-03-22 12:17 UTC, lby9906 commented on src/main/java/back/petionary/application/loss/service/ReportLossReadService.java
> +        ReportLoss reportLoss = reportLossRepository.findByIdAndAccountId(reportLossId, accountId).orElseThrow(() -> new PetionaryException("회원 id에 해당하는 게시물을 찾지 못했습니다."));
그렇네요 수정하겠습니다

2024-03-22 12:24 UTC, cousim46 reviewed
리뷰 내용을 잘 반영해주시는 모습을 보고 욕심이 생겨 코드리뷰를 추가적으로 달았습니다!

2024-03-22 12:24 UTC, cousim46 commented on src/main/java/back/petionary/application/loss/service/ReportLossReadService.java
> +        return new ReportLossResponse(reportLoss.getAccount().getNickName(), reportLoss.getPet().getPetName(), reportLoss.getPet().getPetBirth(), reportLoss.getFeature(), reportLoss.getLossLocation()
일단 여기서 findById를 해서 reportLoss에 대한 1번 발생하게 됩니다. 그런데 return문에 있는  new ReportLossResponse부분에 있는 reportLoss.getAccount().getNickname(), reportLoss.getPet().getPetName(), reportLoss.getPet().getPetBirth() 부분으로 이해 N+1 문제가 발생할거 같아요!
이 로직에서는 추가적으로 account에 대한 쿼리와 pet에 대한 쿼리가 발생할거 같은데 이거를 한번의 쿼리만 발생하게 수정해주실 수 있나요?

만약 쿼리가 발생하는걸 보고싶으시면

```java
 ReportLoss reportLoss = reportLossRepository.findById(reportLossId).orElseThrow(() -> new PetionaryException("해당하는 게시물을 찾을 수 없습니다."));
 
 System.out.println("쿼리확인");

ReportLossResponse response = new ReportLossResponse(reportLoss.getAccount().getNickName(), reportLoss.getPet().getPetName(), reportLoss.getPet().getPetBirth(), reportLoss.getFeature(), reportLoss.getLossLocation(),reportLoss.getLossDateTime(), reportLoss.getContent());
 System.out.println("account, pet 쿼리 확인");

return response;
```

이런식으로 로그로 한번 확인해보세요~

2024-03-22 13:16 UTC, lby9906 commented on src/main/java/back/petionary/application/loss/service/ReportLossReadService.java
> +        return new ReportLossResponse(reportLoss.getAccount().getNickName(), reportLoss.getPet().getPetName(), reportLoss.getPet().getPetBirth(), reportLoss.getFeature(), reportLoss.getLossLocation()
확인하고 수정하겠습니다~

2024-03-28 14:57 UTC, cousim46 approved these changes
머지해도 될거같아요! 고생하셨습니다!

2024-03-29 10:52 UTC, merged